call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue1
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic1
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue2
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic2
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue3
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic3
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue4
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic4
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue5
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic5
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA11 jms/OfficeA11
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA12 jms/OfficeA12
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA13 jms/OfficeA13
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA14 jms/OfficeA14
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA15 jms/OfficeA15
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA21 jms/OfficeA21
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA22 jms/OfficeA22
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA23 jms/OfficeA23
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA24 jms/OfficeA24
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA25 jms/OfficeA25
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=queueTM jms/queueTM1
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=queueTM jms/queueTM2
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice11
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice12
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice13
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice14
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice15
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice21
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice22
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice23
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice24
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice25
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicDistrict1 jms/TopicDistrict1
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicDistrict2 jms/TopicDistrict2
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicDistrict3 jms/TopicDistrict3
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicDistrict4 jms/TopicDistrict4
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicDistrict5 jms/TopicDistrict5
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicCrash1 jms/TopicCrash1
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicCrash2 jms/TopicCrash2
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicCrash3 jms/TopicCrash3
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicCrash4 jms/TopicCrash4
call asadmin.bat --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicCrash5 jms/TopicCrash5
