./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue1
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic1
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue2
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic2
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue3
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic3
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue4
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic4
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryQueue5
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.ConnectionFactory --description "" jms/ViabilityConnectionFactoryTopic5
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA11 jms/OfficeA11
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA12 jms/OfficeA12
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA13 jms/OfficeA13
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA14 jms/OfficeA14
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA15 jms/OfficeA15
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA21 jms/OfficeA21
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA22 jms/OfficeA22
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA23 jms/OfficeA23
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA24 jms/OfficeA24
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=OfficeA25 jms/OfficeA25
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=queueTM jms/queueTM1
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=queueTM jms/queueTM2
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice11
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice12
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice13
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice14
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice15
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice21
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice22
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice23
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice24
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Queue --property Name=DBQueueDistrict1 jms/DBQueueOffice25
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicDistrict1 jms/TopicDistrict1
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicDistrict2 jms/TopicDistrict2
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicDistrict3 jms/TopicDistrict3
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicDistrict4 jms/TopicDistrict4
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicDistrict5 jms/TopicDistrict5
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicCrash1 jms/TopicCrash1
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicCrash2 jms/TopicCrash2
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicCrash3 jms/TopicCrash3
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicCrash4 jms/TopicCrash4
./asadmin --passwordfile password.txt create-jms-resource --restype javax.jms.Topic --property Name=TopicCrash5 jms/TopicCrash5
