./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue1
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic1
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue2
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic2
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue3
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic3
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue4
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic4
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue5
./asadmin --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic5
./asadmin --passwordfile password.txt delete-jms-resource jms/OfficeA11
./asadmin --passwordfile password.txt delete-jms-resource jms/OfficeA12
./asadmin --passwordfile password.txt delete-jms-resource jms/OfficeA13
./asadmin --passwordfile password.txt delete-jms-resource jms/OfficeA14
./asadmin --passwordfile password.txt delete-jms-resource jms/OfficeA15
./asadmin --passwordfile password.txt delete-jms-resource jms/OfficeA21
./asadmin --passwordfile password.txt delete-jms-resource jms/OfficeA22
./asadmin --passwordfile password.txt delete-jms-resource jms/OfficeA23
./asadmin --passwordfile password.txt delete-jms-resource jms/OfficeA24
./asadmin --passwordfile password.txt delete-jms-resource jms/OfficeA25
./asadmin --passwordfile password.txt delete-jms-resource jms/queueTM1
./asadmin --passwordfile password.txt delete-jms-resource jms/queueTM2
./asadmin --passwordfile password.txt delete-jms-resource jms/DBQueueOffice11
./asadmin --passwordfile password.txt delete-jms-resource jms/DBQueueOffice12
./asadmin --passwordfile password.txt delete-jms-resource jms/DBQueueOffice13
./asadmin --passwordfile password.txt delete-jms-resource jms/DBQueueOffice14
./asadmin --passwordfile password.txt delete-jms-resource jms/DBQueueOffice15
./asadmin --passwordfile password.txt delete-jms-resource jms/DBQueueOffice21
./asadmin --passwordfile password.txt delete-jms-resource jms/DBQueueOffice22
./asadmin --passwordfile password.txt delete-jms-resource jms/DBQueueOffice23
./asadmin --passwordfile password.txt delete-jms-resource jms/DBQueueOffice24
./asadmin --passwordfile password.txt delete-jms-resource jms/DBQueueOffice25
./asadmin --passwordfile password.txt delete-jms-resource jms/TopicDistrict1
./asadmin --passwordfile password.txt delete-jms-resource jms/TopicDistrict2
./asadmin --passwordfile password.txt delete-jms-resource jms/TopicDistrict3
./asadmin --passwordfile password.txt delete-jms-resource jms/TopicDistrict4
./asadmin --passwordfile password.txt delete-jms-resource jms/TopicDistrict5
./asadmin --passwordfile password.txt delete-jms-resource jms/TopicCrash1
./asadmin --passwordfile password.txt delete-jms-resource jms/TopicCrash2
./asadmin --passwordfile password.txt delete-jms-resource jms/TopicCrash3
./asadmin --passwordfile password.txt delete-jms-resource jms/TopicCrash4
./asadmin --passwordfile password.txt delete-jms-resource jms/TopicCrash5