call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue1
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic1
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue2
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic2
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue3
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic3
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue4
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic4
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryQueue5
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/ViabilityConnectionFactoryTopic5
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/OfficeA11
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/OfficeA12
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/OfficeA13
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/OfficeA14
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/OfficeA15
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/OfficeA21
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/OfficeA22
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/OfficeA23
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/OfficeA24
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/OfficeA25
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/queueTM1
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/queueTM2
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/DBQueueOffice11
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/DBQueueOffice12
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/DBQueueOffice13
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/DBQueueOffice14
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/DBQueueOffice15
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/DBQueueOffice21
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/DBQueueOffice22
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/DBQueueOffice23
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/DBQueueOffice24
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/DBQueueOffice25
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/TopicDistrict1
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/TopicDistrict2
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/TopicDistrict3
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/TopicDistrict4
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/TopicDistrict5
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/TopicCrash1
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/TopicCrash2
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/TopicCrash3
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/TopicCrash4
call asadmin.bat --passwordfile password.txt delete-jms-resource jms/TopicCrash5